version: '2'

volumes:
  data_volume:
    driver: local

services:
  web:
    image: mkornatz/ubuntu16-apache2-php7.0:latest
    environment:
      APACHE_SERVER_NAME: localhost
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      # This maps http://<docker-host-ip>:8080/ to port 80 of the container
      - "8080:80"
    volumes:
      # Mount the current directory to the container for apache2
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306" # connect to MySQL on mysql://<docker-ip>:13306
    expose:
      - 3306
    volumes:
      - data_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ourlittlesecret
      MYSQL_DATABASE: example
      MYSQL_USER: develop
      MYSQL_PASSWORD: developpass
